# Generated by Django 2.2.28 on 2022-05-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=30)),
                ('married', models.CharField(max_length=30)),
                ('dependents', models.CharField(max_length=30)),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=30)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('applicant_income', models.CharField(max_length=30)),
                ('coapplicant_income', models.CharField(max_length=30)),
                ('loanAmount', models.CharField(max_length=30)),
                ('loan_Amount_term', models.CharField(max_length=30)),
                ('credit_history', models.CharField(max_length=30)),
                ('property_area', models.CharField(choices=[('Urban', 'Urban'), ('Semiurban', 'Semiurban'), ('Rural', 'Rural')], max_length=30)),
            ],
        ),
    ]
