# Generated by Django 2.2.28 on 2022-05-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20220516_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
    ]
