# Generated by Django 2.2.28 on 2022-05-16 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
