# Generated by Django 2.2.28 on 2022-05-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20220519_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='applicant_income',
            field=models.PositiveIntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='coapplicant_income',
            field=models.PositiveIntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanAmount',
            field=models.PositiveIntegerField(max_length=30),
        ),
    ]
