# Generated by Django 4.0.4 on 2022-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='acc_type',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Checking', 'Checking'), ('Current', 'Current'), ('HomeLoan', 'Home Loan'), ('CarLoan', 'Car Loan'), ('PersonalLoan', 'Personal Loan'), ('OtherLoan', 'Other Loan'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Card Payment', 'Card Payment'), ('Interest', 'Interest'), ('Shopping', 'Shopping'), ('EMI/Loan Payment', 'EMI/Loan Payment'), ('Fuel', 'Fuel'), ('Other', 'Other'), ('Groceries', 'Groceries'), ('Rent', 'Rent'), ('Medical', 'Medical'), ('Charity', 'Charity'), ('Investment', 'Investment'), ('Child Education', 'Child Education'), ('Vacation', 'Vacation'), ('Entertainment', 'Entertainment'), ('Utility', 'Utility'), ('Gift', 'Gift'), ('Salary/Payment', 'Salary/Payment'), ('Insurance', 'Insurance')], max_length=100, null=True),
        ),
    ]
