# Generated by Django 4.0.4 on 2022-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Application', 'Application'), ('Action', 'Action'), ('Notification', 'Notification'), ('Marketing', 'Marketing')], default='Notification', max_length=100),
        ),
    ]
